<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class PositionSeeder
 * @package Database\Seeders
 */
class OccupationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared(<<<QUERY
insert into occupation_categories (id, name, deleted_at)
values  (1, 'Management/business management', null),
        (2, 'Planning and Management', null),
        (3, 'Professionals(consulting firms, specialized offices, audit firms)', null),
        (4, 'Sales position', null),
        (5, 'Technical staff (SE/infrastructure engineer/web engineer)', null),
        (6, 'Technical job (embedded software)', null),
        (7, 'Technical job (mechanical/electrical)', null),
        (8, 'Technical/Professional (Construction/Building/Real Estate/Plant/Factory)', null),
        (9, 'Technical staff (chemistry, materials, cosmetics, toiletries)', null),
        (10, 'Technical staff (food, spices, feed)', null),
        (11, 'Medical profession', null),
        (12, 'Financial profession', null),
        (13, 'Creator/creative job', null),
        (14, 'Sales/service staff', null),
        (15, 'Civil servants, teachers, agriculture, forestry and fisheries related jobs', null),
        (16, 'Other', null) on conflict do nothing;
insert into occupations (id, name, occupation_category_id)
values  (1, 'CEO', 1),
        (2, 'COO', 1),
        (3, 'CFO', 1),
        (4, 'CTO/CIO', 1),
        (5, 'CMO', 1),
        (6, 'CHO', 1),
        (7, 'Other CXO', 1),
        (8, 'Business manager', 1),
        (9, 'Management department manager', 1),
        (10, 'Corporate Planning', 2),
        (11, 'M & A/merger/tie-up', 2),
        (12, 'Business planning/new business development', 2),
        (13, 'Sales Planning', 2),
        (14, 'Product planning/service planning', 2),
        (15, 'Advertisement', 2),
        (16, 'Sales promotion/PR', 2),
        (17, 'MD', 2),
        (18, 'Web marketing (online advertising, sales promotion PR, etc.)', 2),
        (19, 'Other marketing/product planning/advertising', 2),
        (20, 'Research/market research', 2),
        (21, 'Data Analyst/Data Scientist', 2),
        (22, 'Accounting (financial accounting)', 2),
        (23, 'Finance', 2),
        (24, 'Management accounting', 2),
        (25, 'Internal control', 2),
        (26, 'Personnel (recruitment/education)', 2),
        (27, 'Personnel (salary company insurance)', 2),
        (28, 'Personnel (labor/personnel system)', 2),
        (29, 'Other personnel', 2),
        (30, 'public relations', 2),
        (31, 'IR', 2),
        (32, 'Purchasing/Procurement/Buyer/MD', 2),
        (33, 'Indirect purchasing/general affairs purchasing', 2),
        (34, 'SCM planning/logistics planning/demand forecast', 2),
        (35, 'Logistics management (vendor management, delivery management, order management, etc.)', 2),
        (36, 'Trade business (import/export business, customs clearance, etc.)', 2),
        (37, 'Warehouse management/inventory management', 2),
        (38, 'General affairs', 2),
        (39, 'Legal', 2),
        (40, 'Intellectual property/patent', 2),
        (41, 'Secretary', 2),
        (42, 'Internal audit', 2),
        (43, 'compliance', 2),
        (44, 'Risk management', 2),
        (45, 'Strategy/Management Consultant', 3),
        (46, 'Organization/Personnel Consultant', 3),
        (47, 'Business Process Reengineering Consultant (BPR)', 3),
        (48, 'Accounting Consultant/Financial Advisory', 3),
        (49, 'Industry consultant', 3),
        (50, 'Marketing consultant', 3),
        (51, 'Logistics consultant', 3),
        (52, 'Manufacturing consultant (product development/production technology/quality control)', 3),
        (53, 'Risk consultant', 3),
        (54, 'Other business consultants', 3),
        (55, 'Industry consultant', 3),
        (56, 'ERP implementation consultant', 3),
        (57, 'Cloud implementation consultant', 3),
        (58, 'Advanced technology consultant (AI/robot, etc.)', 3),
        (59, 'Analytics consultant', 3),
        (60, 'IT risk consultant', 3),
        (61, 'Security consultant', 3),
        (62, 'Infrastructure consultant', 3),
        (63, 'Other IT consultants', 3),
        (64, 'Accounting profession/accountant', 3),
        (65, 'Tax accountant', 3),
        (66, 'lawyer', 3),
        (67, 'Patent attorney/patent engineer', 3),
        (68, 'Judicial scrivener', 3),
        (69, 'Administrative scrivener', 3),
        (70, 'Social insurance labor consultant', 3),
        (71, 'IT corporate sales (direct sales)', 4),
        (72, 'IT corporation sales (agency)', 4),
        (73, 'Web-based solution sales', 4),
        (74, 'IT private business', 4),
        (75, 'Semiconductor/electronic parts/electronics product sales (domestic)', 4),
        (76, 'Semiconductor/electronic parts/electronics product sales (overseas)', 4),
        (77, 'Equipment/Machine Tool/Industrial Machinery Sales (Domestic)', 4),
        (78, 'Equipment/Machine Tool/Industrial Machinery Sales (Overseas)', 4),
        (79, 'Precision machinery/measuring equipment/analytical equipment/optical product sales (domestic)', 4),
        (80, 'Precision machinery/measuring equipment/analytical equipment/optical product sales (overseas)', 4),
        (81, 'Sales of automobiles, construction machinery, and automobile parts (domestic)', 4),
        (82, 'Sales of automobiles, construction machinery, and automobile parts (overseas)', 4),
        (83, 'Raw material/material/chemical product sales (domestic)', 4),
        (84, 'Raw material/material/chemical product sales (overseas)', 4),
        (85, 'MR', 4),
        (86, 'Medical equipment sales', 4),
        (87, 'OTC (over-the-counter drug)', 4),
        (88, 'MS/Pharmaceutical Wholesale/Distributor', 4),
        (89, 'Life science (physical and chemical equipment/reagents)', 4),
        (90, 'Other medical sales', 4),
        (91, 'Food/Beverage Sales (Domestic)', 4),
        (92, 'Daily necessities/cosmetics business (domestic)', 4),
        (93, 'Other consumer goods business (domestic)', 4),
        (94, 'Food/Beverage/Daily Necessities/Cosmetics/Other Consumer Goods Sales (Overseas)', 4),
        (95, 'Construction/real estate corporation business', 4),
        (96, 'Construction/real estate private business', 4),
        (97, 'Financial corporation business', 4),
        (98, 'Financial Individual Sales/Financial Planner', 4),
        (99, 'Advertising/media corporate sales (new focus)', 4),
        (100, 'Advertising/media corporate sales (mainly existing/route sales)', 4),
        (101, 'Advertising/media agency sales/partner sales', 4),
        (102, 'Advertising/media individual business', 4),
        (103, 'Advertising/Media Overseas Sales', 4),
        (104, 'Dispatch business', 4),
        (105, 'Dispatch coordinator', 4),
        (106, 'Human resources introduction sales', 4),
        (107, 'Job advertisement sales', 4),
        (108, 'Career Consultant/Career Advisor', 4),
        (109, 'Boutique executive', 4),
        (110, 'Other sales positions', 4),
        (111, 'Other corporate sales (new center)', 4),
        (112, 'Other corporate sales (mainly existing/route sales)', 4),
        (113, 'Other agency sales/partner sales', 4),
        (114, 'Other private business', 4),
        (115, 'Other overseas sales', 4),
        (116, 'Project manager (Web/open system/package development)', 5),
        (117, 'System engineer (Web/open system/package development)', 5),
        (118, 'System engineer (general-purpose machine)', 5),
        (119, 'Architect', 5),
        (120, 'Package introduction/system introduction', 5),
        (121, 'Web Services Project Manager', 5),
        (122, 'Web service engineer (front end, server side, full stack)', 5),
        (123, 'Smartphone app/native app project manager', 5),
        (124, 'Smartphone app/native app engineer', 5),
        (125, 'Project manager (infrastructure)', 5),
        (126, 'Web service engineer (network server database)', 5),
        (127, 'Server engineer (design and construction)', 5),
        (128, 'Network engineer (design and construction)', 5),
        (129, 'Database engineer', 5),
        (130, 'Operation/monitoring/maintenance', 5),
        (131, 'In charge of IT strategy and system planning', 5),
        (132, 'System development and operation (in charge of applications)', 5),
        (133, 'System construction and operation (infrastructure charge)', 5),
        (134, 'Technical support/customer support (IT products)', 5),
        (135, 'Security consultant/analyst', 5),
        (136, 'Security engineer (application)', 5),
        (137, 'Security engineer (network security)', 5),
        (138, 'Data Scientist Analyst', 5),
        (139, 'Data scientist engineering', 5),
        (140, 'Research and Development (R & D) Engineer', 5),
        (141, 'QA/tester', 5),
        (142, 'Control software development (communication/network/IoT related)', 5),
        (143, 'Basic research/advanced development/elemental technology development', 6),
        (144, 'Project manager', 6),
        (145, 'Mechanical/electronic parts', 6),
        (146, 'Home appliances/AV equipment/multifunction devices', 6),
        (147, 'Pachinko/pachislot/play equipment', 6),
        (148, 'Medical equipment', 6),
        (149, 'Smartphone app/native app engineer', 6),
        (150, 'Wireless/communication equipment', 6),
        (151, 'semiconductor', 6),
        (152, 'Precision/measurement/analysis equipment', 6),
        (153, 'Storage (HDD, SSD, etc.)', 6),
        (154, 'Automobiles, automobile parts, in-vehicle products', 6),
        (155, 'Construction machinery and other transportation equipment', 6),
        (156, 'Machine tools, industrial machines, semiconductor manufacturing equipment, industrial robots', 6),
        (157, 'Robots (working robots, powered suits, etc.)', 6),
        (158, 'Other applications, middleware, device drivers, firmware', 6),
        (159, 'iOS/Android', 6),
        (160, 'Network/IoT', 6),
        (161, 'Home appliances/AV equipment/multifunction devices', 6),
        (162, 'Mechanical/electronic parts', 6),
        (163, 'Medical equipment', 6),
        (164, 'Smartphones/tablets/mobile terminals', 6),
        (165, 'Wireless/communication equipment', 6),
        (166, 'Automobiles, automobile parts, in-vehicle products', 6),
        (167, 'Machine tools, industrial machines, semiconductor manufacturing equipment, industrial robots', 6),
        (168, 'Other quality control, quality assurance, technical support (embedded software)', 6),
        (169, 'Evaluation/debugging', 6),
        (170, 'User interface', 6),
        (171, 'Image processing', 6),
        (172, 'Speech processing', 6),
        (173, 'Pre-sales application engineer (for the automobile industry)', 6),
        (174, 'Pre-sales (for other industries)', 6),
        (175, 'Consulting (quality, development process, etc.)', 6),
        (176, 'Basic research/advanced development/elemental technology development (machinery)', 7),
        (177, 'Basic research/advanced development/elemental technology development (electricity)', 7),
        (178, 'Product Planning/Project Manager (Machine)', 7),
        (179, 'Product Planning/Project Manager (Electricity)', 7),
        (180, 'Mechanical/electronic components/connectors', 7),
        (181, 'Home appliances, AV, smartphones, mobile terminals, multifunction devices', 7),
        (182, 'Medical equipment', 7),
        (183, 'Precision/measurement/analysis equipment', 7),
        (184, 'Automobiles/Auto parts', 7),
        (185, 'Machine tools/industrial machines/robots', 7),
        (186, 'Semiconductor manufacturing equipment', 7),
        (187, 'Other mechanical design', 7),
        (188, 'Pachinko/pachislot/play equipment', 7),
        (189, 'Wireless/communication equipment', 7),
        (190, 'Construction machinery and other transportation equipment', 7),
        (191, 'Plant equipment/equipment', 7),
        (192, 'Press die', 7),
        (193, 'Injection molding mold', 7),
        (194, 'Other mold design', 7),
        (195, 'Analog (power supply)', 7),
        (196, 'Analog (power electronics)', 7),
        (197, 'Analog (high frequency/RF/communication)', 7),
        (198, 'Analog (Other analog)', 7),
        (199, 'Digital (microcomputer/CPU/DSP)', 7),
        (200, 'Digital (FPGA)', 7),
        (201, 'Digital (Other Digital)', 7),
        (202, 'Layout design', 7),
        (203, 'Semiconductor/IC (analog)', 7),
        (204, 'Semiconductor/IC (digital)', 7),
        (205, 'Semiconductor/IC (memory)', 7),
        (206, 'Semiconductors/ICs (other ICs)', 7),
        (207, 'Optical design', 7),
        (208, 'Sequence control (PLC/sequence/ladder)', 7),
        (209, 'Electrical design (machine tools, equipment, equipment, control panels, etc.)', 7),
        (210, 'Process design, construction method development, process improvement, IE (resin molding)', 7),
        (211, 'Process design/construction method development/process improvement/IE (assembly/assembly)', 7),
        (212, 'Process design, construction method development, process improvement, IE (machinery, metal processing)', 7),
        (213, 'Process design, construction method development, process improvement, IE (others)', 7),
        (214, 'Equipment startup/design (mechanical design)', 7),
        (215, 'Equipment start-up/design (electrical/control design)', 7),
        (216, 'Equipment maintenance', 7),
        (217, 'Machine/metal processing', 7),
        (218, 'Assembly/Other Manufacturing', 7),
        (219, 'Production control', 7),
        (220, 'Factory manager', 7),
        (221, 'Device development (power semiconductor)', 7),
        (222, 'Device development (LED/light emitting device/optical semiconductor)', 7),
        (223, 'Device development (memory)', 7),
        (224, 'Device development (other semiconductors)', 7),
        (225, 'Device development (solar, LCD, etc.)', 7),
        (226, 'Device development (sensor)', 7),
        (227, 'Process integration', 7),
        (228, 'Process engineer (pre-process)', 7),
        (229, 'Process engineer (post-process)', 7),
        (230, 'Quality control (machine)', 7),
        (231, 'Quality control (electrical/electronic/semiconductor)', 7),
        (232, 'Quality Assurance (Machine)', 7),
        (233, 'Quality Assurance (Electrical/Electronic/Semiconductor)', 7),
        (234, 'Mechanical/electronic components/connectors', 7),
        (235, 'Home appliances, AV, mobile terminals, multifunction devices', 7),
        (236, 'Medical equipment', 7),
        (237, 'Precision/measurement/analysis equipment', 7),
        (238, 'Automobiles/Auto parts', 7),
        (239, 'Construction machinery and other transportation equipment', 7),
        (240, 'semiconductor', 7),
        (241, 'Semiconductor manufacturing equipment', 7),
        (242, 'Base station/wireless equipment/communication equipment', 7),
        (243, 'Machine tools/industrial machines/robots', 7),
        (244, 'Plant equipment/equipment', 7),
        (245, 'Software (CAD/CAM/CAE)', 7),
        (246, 'Software (Other)', 7),
        (247, 'Other sales engineers, application engineers, FAE', 7),
        (248, 'Mechanical/electronic parts', 7),
        (249, 'Home appliances, AV, mobile terminals, multifunction devices', 7),
        (250, 'Medical equipment', 7),
        (251, 'Precision/measurement/analysis equipment', 7),
        (252, 'Automobiles, aviation, construction machinery, and other transportation equipment', 7),
        (253, 'Machine tools/industrial machines/robots', 7),
        (254, 'Semiconductor manufacturing equipment', 7),
        (255, 'Base station/wireless equipment/communication equipment', 7),
        (256, 'Plant equipment/equipment', 7),
        (257, 'Other service engineers', 7),
        (258, 'CAD operator (machine)', 7),
        (259, 'CAE analysis (heat/fluid)', 7),
        (260, 'CAE analysis (structure/stress/collision/vibration)', 7),
        (261, 'CAE analysis (electromagnetic field/electromagnetic field)', 7),
        (262, 'CAE analysis (others)', 7),
        (263, 'Evaluation/Experiment (Machine)', 7),
        (264, 'Evaluation/Experiment (Electrical/Electronic/Semiconductor)', 7),
        (265, 'mechanic', 7),
        (266, 'Mechanic (automobile, construction equipment, aircraft, etc.)', 7),
        (267, 'Technical writer', 7),
        (268, 'Other technical positions (mechanical/electrical)', 7),
        (269, 'Real estate development planning', 8),
        (270, 'Construction management/PM/FM (owner side)', 8),
        (271, 'Real estate purchase (land/building/division)', 8),
        (272, 'Due diligence (architecture)', 8),
        (273, 'Due diligence (real estate appraisal)', 8),
        (274, 'Quality control/safety management (technical)', 8),
        (275, 'Asset management', 8),
        (276, 'Property management (office)', 8),
        (277, 'Property management (commercial facilities/others)', 8),
        (278, 'Property management (housing/rental management)', 8),
        (279, 'Building management', 8),
        (280, 'Condominium management', 8),
        (281, 'Condominium management (technical)', 8),
        (282, 'After-maintenance (apartment/detached house)', 8),
        (283, 'Building management (commercial facilities, stores, offices)', 8),
        (284, 'Building maintenance (commercial facilities, stores, offices)', 8),
        (285, 'Technology development/material development/analysis/survey', 8),
        (286, 'Technology development/construction method development (architecture/civil engineering)', 8),
        (287, 'Material development/building material development (building/civil engineering)', 8),
        (288, 'Structural analysis/seismic diagnosis (architecture/civil engineering)', 8),
        (289, 'Design design', 8),
        (290, 'Structural design', 8),
        (291, 'Drafting/CAD operator (construction)', 8),
        (292, 'Interior design/interior', 8),
        (293, 'Accumulation', 8),
        (294, 'Design supervision', 8),
        (295, 'Interior design (store)', 8),
        (296, 'Interior design/remodeling/interior (house)', 8),
        (297, 'Interior design (office)', 8),
        (298, 'Architectural construction management (RC structure, S structure, SRC structure)', 8),
        (299, 'Architectural construction management (wooden construction)', 8),
        (300, 'Architectural construction management (store interior)', 8),
        (301, 'Architectural construction management (house interior, remodeling, interior)', 8),
        (302, 'Architectural construction management (office interior)', 8),
        (303, 'Equipment construction management (electricity)', 8),
        (304, 'Equipment construction management (air conditioning/sanitary equipment)', 8),
        (305, 'Equipment construction management (communication equipment/firefighting/disaster prevention equipment)', 8),
        (306, 'Civil engineering construction management (bridge)', 8),
        (307, 'Civil engineering construction management (tunnels, roads, construction, dams, rivers, harbors, landscaping, etc.)', 8),
        (308, 'Civil engineering construction management (water and sewage)', 8),
        (309, 'Other equipment construction management', 8),
        (310, 'electrical equipment', 8),
        (311, 'Air conditioning and sanitation equipment', 8),
        (312, 'Communication equipment/firefighting/disaster prevention equipment', 8),
        (313, 'Drafting/CAD operator (construction)', 8),
        (314, 'Accumulation', 8),
        (315, 'Civil engineering design/survey (city planning/environment)', 8),
        (316, 'Civil engineering design/surveying (bridge)', 8),
        (317, 'Civil engineering design/survey (tunnel/road/construction)', 8),
        (318, 'Civil engineering design/surveying (dams, rivers, harbors)', 8),
        (319, 'Civil engineering design and surveying (water and sewage)', 8),
        (320, 'Drafting/CAD operator (construction)', 8),
        (321, 'Surveying', 8),
        (322, 'Soil/geology/ground survey', 8),
        (323, 'Project management (domestic)', 8),
        (324, 'Project management (overseas)', 8),
        (325, 'Design (architecture/civil engineering)', 8),
        (326, 'Design (electricity/instrumentation)', 8),
        (327, 'Design (machine)', 8),
        (328, 'Design (process)', 8),
        (329, 'Construction management (building/civil engineering)', 8),
        (330, 'Construction management (electricity/instrumentation)', 8),
        (331, 'Construction management (machine)', 8),
        (332, 'Procurement', 8),
        (333, 'Operation/test run', 8),
        (334, 'Analysis/Survey', 8),
        (335, 'maintenance', 8),
        (336, 'Factory Facility Utility (Electrical/Air Conditioning Hygiene)', 8),
        (337, 'Occupational Safety and Health (EHS/HSE)', 8),
        (338, 'Carpenters, jumpers, plasterers, equipment, etc.', 8),
        (339, 'Other construction/construction/real estate/plant/factory related jobs', 8),
        (340, 'Basic/Applied Research (Organic)', 9),
        (341, 'Basic/Applied Research (Polymer)', 9),
        (342, 'Basic/Applied Research (Glass/Ceramic)', 9),
        (343, 'Basic/Applied Research (Carbon)', 9),
        (344, 'Basic/Applied Research (Metal/Steel)', 9),
        (345, 'Basic/Applied Research (Nonferrous Metals)', 9),
        (346, 'Basic/Applied Research (Other Inorganic)', 9),
        (347, 'Basic/Applied Research (Cosmetics/Toiletries)', 9),
        (348, 'Product development (organic)', 9),
        (349, 'Product development (polymer)', 9),
        (350, 'Product development (glass/ceramic)', 9),
        (351, 'Product development (carbon)', 9),
        (352, 'Product development (metal/steel)', 9),
        (353, 'Product development (non-ferrous metal)', 9),
        (354, 'Product development (other inorganic)', 9),
        (355, 'Product development (organic metals, complexes, catalysts)', 9),
        (356, 'Product development (cosmetics/toiletries)', 9),
        (357, 'Manufacturing process development/construction method development (synthesis/polymerization)', 9),
        (358, 'Manufacturing process development/construction method development (blending design products) (paints, adhesives, etc.)', 9),
        (359, 'Manufacturing process development/construction method development (processing and molding) (resin)', 9),
        (360, 'Manufacturing process development/construction method development (processing and molding) (metal/steel/glass)', 9),
        (361, 'Manufacturing process development/construction method development (inorganic/ceramic/non-ferrous metal)', 9),
        (362, 'Manufacturing process development/construction method development (semiconductor, solar power, liquid crystal, LED, etc.)', 9),
        (363, 'Manufacturing process development/construction method development (cosmetics/toiletries)', 9),
        (364, 'Production control (chemistry, materials, cosmetics, toiletries)', 9),
        (365, 'Quality control (chemicals, chemicals, chemical raw materials, etc.)', 9),
        (366, 'Quality control (processed molded products, resins, metals, steel, glass, etc.)', 9),
        (367, 'Quality control (cosmetics/toiletries)', 9),
        (368, 'Quality Assurance/Audit (Chemicals, Chemicals, Chemical Raw Materials, etc.)', 9),
        (369, 'Quality Assurance/Audit (Processed Molded Products) (Resin, Metal, Steel, Glass, etc.)', 9),
        (370, 'Chemical regulations', 9),
        (371, 'Quality Assurance/Audit', 9),
        (372, 'Application/Pharmaceutical Affairs', 9),
        (373, 'Technical sales/application engineer (chemistry/materials/cosmetics/toiletries)', 9),
        (374, 'Technical support (technical support position)', 9),
        (375, 'Factory manager (chemistry, materials, cosmetics, toiletries)', 9),
        (376, 'Manufacturing/Production Leader(Chemistry)', 9),
        (377, 'Manufacturing/production operator(Chemistry)', 9),
        (378, 'Manufacturing/Production Leader (Cosmetics/Toiletries)', 9),
        (379, 'Manufacturing/production operator (Cosmetics/Toiletries)', 9),
        (380, 'Analysis/analysis/measurement/various evaluation tests (chemistry)', 9),
        (381, 'Analysis/analysis/measurement/various evaluation tests (cosmetics/toiletries)', 9),
        (382, 'Other manufacturing/production', 9),
        (383, 'Basic/applied research (food raw materials/functional raw materials)', 10),
        (384, 'Basic/Applied Research (Food Applications)', 10),
        (385, 'Basic/Applied Research (Food Menu Development/Preparation/Eating Out)', 10),
        (386, 'Basic/applied research (fragrance)', 10),
        (387, 'Basic/applied research (feed/pet food)', 10),
        (388, 'Product development (food raw materials/functional raw materials)', 10),
        (389, 'Product development (food application)', 10),
        (390, 'Product development (food menu development, prepared meals, eating out)', 10),
        (391, 'Product development (fragrance)', 10),
        (392, 'Product development (feed/pet food)', 10),
        (393, 'Manufacturing process development/construction method development (food/beverage plant)', 10),
        (394, 'Manufacturing process development/construction method development (manufacturing line)', 10),
        (395, 'Production control (food, spices, feed)', 10),
        (396, 'Quality control (food, spices, feed)', 10),
        (397, 'Quality Assurance/Audit (Food/Flavor/Feed)', 10),
        (398, 'Technical sales/application engineer (food/fragrance/feed)', 10),
        (399, 'Technical support (technical support) (food, spices, feed)', 10),
        (400, 'Manufacturing/Production Leader (Food/Flavor/Feed)', 10),
        (401, 'Manufacturing/Production Operator (Food/Flavor/Feed)', 10),
        (402, 'Analysis/analysis/measurement/various evaluation tests (food/fragrance/feed)', 10),
        (403, 'Factory manager (food, spices, feed)', 10),
        (404, 'Research (seeds search/screening)', 11),
        (405, 'Non-clinical studies (pharmacokinetics/GLP)', 11),
        (406, 'Nonclinical studies (safety/toxicity/GLP)', 11),
        (407, 'Pharmaceutical research (prescription design)', 11),
        (408, 'Research (basic research)', 11),
        (409, 'Analytical research', 11),
        (410, 'Research (bioinformatics)', 11),
        (411, 'Pharmaceutical research (scale-up/industrialization)', 11),
        (412, 'Non-clinical research (pharmacology/GLP)', 11),
        (413, 'Manufacturing process/construction method development (regenerative medicine products)', 11),
        (414, 'Application (OTC/quasi-drug)', 11),
        (415, 'Pharmaceutical Development Pharmaceutical Affairs', 11),
        (416, 'Pharmaceuticals CMC Pharmaceutical Affairs', 11),
        (417, 'Market access/drug price strategy', 11),
        (418, 'Application (medical equipment)', 11),
        (419, 'Clinical planning (protocol creation)', 11),
        (420, 'Study Manager/Project Manager', 11),
        (421, 'CRA (Clinical Research Associate)', 11),
        (422, 'Clinical research', 11),
        (423, 'CRC (Clinical Trial Coordinator)', 11),
        (424, 'Statistical analysis', 11),
        (425, 'DM (Data Management)', 11),
        (426, 'QC (Clinical Quality Control)', 11),
        (427, 'GCP Audit/QA (Clinical Development QA)', 11),
        (428, 'Clinical pharmacology', 11),
        (429, 'MW (Medical Writing)', 11),
        (430, 'SMA (Clinical Trial Secretariat)', 11),
        (431, 'Medical Doctor (Clinical/Clinical Development)', 11),
        (432, 'Medical Doctor (Safety/PV)', 11),
        (433, 'PMS (Post-marketing surveillance)', 11),
        (434, 'PV (Safety Information)', 11),
        (435, 'Pharmaceutical Quality Control/Testing (QC) (Manufacturing Plant)', 11),
        (436, 'Pharmaceutical Quality Assurance (QA) (Headquarters)', 11),
        (437, 'Pharmaceutical Quality Assurance (QA) (Manufacturing Factory)', 11),
        (438, 'Medical Device Quality Control/Quality Assurance (GQP/QMS)', 11),
        (439, 'Medical Device Safety Management (GVP)', 11),
        (440, 'Production control', 11),
        (441, 'Manufacturing operator', 11),
        (442, 'Manufacturing process management/process improvement', 11),
        (443, 'Factory manager', 11),
        (444, 'Technical Sales/Application Specialist', 11),
        (445, 'Clinical specialist', 11),
        (446, 'Academic/DI', 11),
        (447, 'Medical Science Liaison Medical Affairs', 11),
        (448, 'Medical Doctor (Affairs/Academic)', 11),
        (449, 'Product manager', 11),
        (450, 'research', 11),
        (451, 'Marketing communications', 11),
        (452, 'Licensing', 11),
        (453, 'Hospital director/secretary', 11),
        (454, 'Doctor', 11),
        (455, 'nurse', 11),
        (456, 'Dentist', 11),
        (457, 'Dental hygienist/dental technician', 11),
        (458, 'Clinical psychologist/counselor', 11),
        (459, 'Dietitian/registered dietitian', 11),
        (460, 'Laboratory technician', 11),
        (461, 'Radiological technologist', 11),
        (462, 'Public health nurse', 11),
        (463, 'Veterinarian', 11),
        (464, 'Clinical engineer', 11),
        (465, 'Other medical/nursing', 11),
        (466, 'Pharmacist/management pharmacist', 11),
        (467, 'Registered seller', 11),
        (468, 'Director/welfare facility director', 11),
        (469, 'Care welfare worker/care manager', 11),
        (470, 'Home helper/care worker', 11),
        (471, 'Caseworker', 11),
        (472, 'Structured finance', 12),
        (473, 'Project finance', 12),
        (474, 'Publication/Underwriting', 12),
        (475, 'M & A', 12),
        (476, 'Other investment banks', 12),
        (477, 'Financial product development', 12),
        (478, 'Actuary', 12),
        (479, 'Quants (development)', 12),
        (480, 'Other development', 12),
        (481, 'Dealer/Trader', 12),
        (482, 'Fund manager', 12),
        (483, 'Quants (operation)', 12),
        (484, 'Other operations', 12),
        (485, 'economist', 12),
        (486, 'Strategist', 12),
        (487, 'Analyst', 12),
        (488, 'Debt Collection', 12),
        (489, 'Loan examination (corporation)', 12),
        (490, 'Loan/contract examination (individual)', 12),
        (491, 'Payment assessment', 12),
        (492, 'Underwriting assessment', 12),
        (493, 'Middle office', 12),
        (494, 'settlement', 12),
        (495, 'Accounting', 12),
        (496, 'Custodian', 12),
        (497, 'Other back office', 12),
        (498, 'Producer/Director/Planner', 13),
        (499, 'art director', 13),
        (500, 'Designer (graphics, etc.)', 13),
        (501, 'Editor/Reporter/Writer', 13),
        (502, 'DTP', 13),
        (503, 'Other publishing/advertising/sales promotion/printing related', 13),
        (504, 'Producer/Director/Planner', 13),
        (505, 'Writer/Scenario Writer', 13),
        (506, 'Sound creator', 13),
        (507, 'AP/AD/Production progress management', 13),
        (508, 'Production technology (live-action, animation, sound, camera, stage)', 13),
        (509, 'Entertainment manager', 13),
        (510, 'Other video/sound/event/entertainment related', 13),
        (511, 'Fashion designer/patterner/stylist', 13),
        (512, 'VMD', 13),
        (513, 'Other fashion (apparel, accessories, textiles)', 13),
        (514, 'Product Designer/Industrial Designer (Industrial Designer)', 13),
        (515, 'Web Producer/Web Director/Web Planner', 13),
        (516, 'art director', 13),
        (517, 'Web designer', 13),
        (518, 'Markup engineer, coder, front-end engineer (web/mobile)', 13),
        (519, 'Web editing/web writer', 13),
        (520, 'Assistant director/production progress management', 13),
        (521, 'UI/UX designer', 13),
        (522, 'Game Producer/Director/Planner', 13),
        (523, 'art director', 13),
        (524, 'Game programmer', 13),
        (525, 'Markup engineer, coder, front-end engineer (game)', 13),
        (526, 'UI/UX designer', 13),
        (527, 'Game designer/illustrator', 13),
        (528, 'CG designer', 13),
        (529, 'Sound creator', 13),
        (530, 'Debug', 13),
        (531, 'Other creative jobs', 13),
        (532, 'Area manager/supervisor', 14),
        (533, 'Facility manager', 14),
        (534, 'Store development/FC development', 14),
        (535, 'Store manager', 14),
        (536, 'Sales/customer service/sales floor charge', 14),
        (537, 'Hall staff, floor staff, cooking staff (food and drink)', 14),
        (538, 'Call center director', 14),
        (539, 'supervisor', 14),
        (540, 'Customer Support User Support Operator', 14),
        (541, 'Hairdresser and other cosmetologists', 14),
        (542, 'Beauty staff, beautician, massage', 14),
        (543, 'Travel arranger/tour conductor/tour conductor', 14),
        (544, 'Facility management/management', 14),
        (545, 'Front desk business/reservation reception', 14),
        (546, 'Other accommodations/hotels', 14),
        (547, 'Road passenger/freight transportation', 14),
        (548, 'Air/Railway/Ship Transport', 14),
        (549, 'Warehousing business', 14),
        (550, 'Cleaning/security/guard', 14),
        (551, 'School manager/manager', 14),
        (552, 'Lecturer/instructor/instructor', 14),
        (553, 'Buyer Distributor', 14),
        (554, 'Merchandiser', 14),
        (555, 'Bridal coordinator/wedding planner', 14),
        (556, 'Funeral director planner', 14),
        (557, 'Other bridal and funeral related', 14),
        (558, 'Prosecutor/Judge/Court official', 15),
        (559, 'Parliamentary staff', 15),
        (560, 'Police officers, firefighters, Defense Agency staff, SDF personnel', 15),
        (561, 'Other civil servants', 15),
        (562, 'University lecturer', 15),
        (563, 'Elementary, middle and high school teachers', 15),
        (564, 'Nursery teacher/kindergarten teacher', 15),
        (565, 'Agriculture, forestry and fisheries related', 15),
        (566, 'Other', 16) on conflict do nothing;
        -- delete if there's any duplicate
        delete from occupations
        where id not in (select max(id)
                 from occupations
                 group by name)
QUERY
        );


    }
}
